import sqlite3


def insert_web_visit_event(
    conn: sqlite3.Connection,
    *,
    anon_id: str,
    session_id: str,
    event_type: str,
    page_path: str,
    occurred_at: str,
    is_bot: bool,
    page_query: str | None = None,
    client_tz: str | None = None,
    client_lang: str | None = None,
    platform: str | None = None,
    user_agent: str | None = None,
    referrer_url: str | None = None,
    referrer_domain: str | None = None,
    utm_source: str | None = None,
    utm_medium: str | None = None,
    utm_campaign: str | None = None,
    utm_term: str | None = None,
    utm_content: str | None = None,
    screen_width: int | None = None,
    screen_height: int | None = None,
    viewport_width: int | None = None,
    viewport_height: int | None = None,
    browser_family: str = "other",
    device_type: str = "unknown",
    os_family: str = "other",
) -> None:
    cursor = conn.cursor()
    cursor.execute(
        """
        INSERT INTO web_visit_event (
            anon_id,
            session_id,
            event_type,
            page_path,
            page_query,
            occurred_at,
            client_tz,
            client_lang,
            platform,
            user_agent,
            is_bot,
            referrer_url,
            referrer_domain,
            utm_source,
            utm_medium,
            utm_campaign,
            utm_term,
            utm_content,
            screen_width,
            screen_height,
            viewport_width,
            viewport_height,
            browser_family,
            device_type,
            os_family
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            anon_id,
            session_id,
            event_type,
            page_path,
            page_query,
            occurred_at,
            client_tz,
            client_lang,
            platform,
            user_agent,
            1 if is_bot else 0,
            referrer_url,
            referrer_domain,
            utm_source,
            utm_medium,
            utm_campaign,
            utm_term,
            utm_content,
            screen_width,
            screen_height,
            viewport_width,
            viewport_height,
            browser_family,
            device_type,
            os_family,
        ),
    )
